name: Testing Secret Variables

on: 
  workflow_dispatch

env: 
  ACTIONS_STEP_DEBUG: true

jobs: 
  test_context-variables:
    runs-on: ubuntu-latest
    steps: 
      - name: "Checking secret variable"
        run: |
          echo "Secrets value : ${{ secrets.MY_KEY }}"
          ${{ secrets.MY_KEY }}
