name: Test User Input workflow

# Control when the action will run. Workflow runs when manually triggered using the UI or API.
on: 
  workflow_dispatch:
    inputs:
      number1:
        description: 'First number'
        default: '0'
        required: true
        type: string
      number2:  
        description: 'Second number'
        default: '0'
        required: true
        type: string

jobs: 
  add_numbers:
    runs-on: ubuntu-latest
    steps: 
      - name: Add numbers
        id: sum
        run: |
          sum=$(( ${{ inputs.number1 }} + ${{ inputs.number2 }} ))
          echo "sum=$sum" >> $GITHUB_OUTPUT

      - name: Display sum 
        run: echo "The sum of ${{ inputs.number1 }} and ${{ inputs.number2 }} is ${{ steps.sum.outputs.sum }}"
